### ISSUE TITLE
Unable to compile the dependencies (error: no matching function for call to)

### ISSUE THREAD

**Issue by student-t** [wtsi-svi/ReadServer#16]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/garvan/Sources/ReadServer/submodules/bamtools/build
[  0%] Built target SharedHeaders
[ 38%] Built target BamTools
[ 38%] Built target AlgorithmsHeaders
[ 76%] Built target BamTools-static
[ 76%] Built target APIHeaders
[ 80%] Built target jsoncpp
[ 85%] Built target BamTools-utils
[ 86%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘bool BamTools::ResolveTool::ReadNamesFileReader::Read(std::map<std::__cxx11::basic_string<char>, ReadGroupResolver>&)’:
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:413:74: error: no matching function for call to ‘make_pair(__gnu_cxx::__alloc_traits<std::allocator<std::__cxx11::basic_string<char> > >::value_type&, bool)’
         resolver.ReadNames.insert( make_pair<string,bool>(fields[1], true) ) ;
                                                                          ^
In file included from /usr/include/c++/6/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6/bits/char_traits.h:39,
                 from /usr/include/c++/6/string:40,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:413:74: note:   cannot convert ‘fields.std::vector<_Tp, _Alloc>::operator[]<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > >(1ul)’ (type ‘__gnu_cxx::__alloc_traits<std::allocator<std::__cxx11::basic_string<char> > >::value_type {aka std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
         resolver.ReadNames.insert( make_pair<string,bool>(fields[1], true) ) ;
                                                                          ^
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘bool BamTools::ResolveTool::StatsFileReader::ParseReadGroupLine(const string&, std::map<std::__cxx11::basic_string<char>, ReadGroupResolver>&)’:
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:610:75: error: no matching function for call to ‘make_pair(const string&, ReadGroupResolver&)’
     readGroups.insert( make_pair<string, ReadGroupResolver>(name, resolver) );
                                                                           ^
In file included from /usr/include/c++/6/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6/bits/char_traits.h:39,
                 from /usr/include/c++/6/string:40,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:610:61: note:   cannot convert ‘name’ (type ‘const string {aka const std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
     readGroups.insert( make_pair<string, ReadGroupResolver>(name, resolver) );
                                                             ^~~~
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘bool BamTools::ResolveTool::ResolveToolPrivate::MakeStats()’:
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:1017:93: error: no matching function for call to ‘make_pair(std::__cxx11::string&, const bool&)’
         else resolver.ReadNames.insert( make_pair<string, bool>(al.Name, isCurrentMateUnique) );
                                                                                             ^
In file included from /usr/include/c++/6/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6/bits/char_traits.h:39,
                 from /usr/include/c++/6/string:40,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:1017:68: note:   cannot convert ‘al.BamTools::BamAlignment::Name’ (type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
         else resolver.ReadNames.insert( make_pair<string, bool>(al.Name, isCurrentMateUnique) );
                                                                 ~~~^~~~
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘void BamTools::ResolveTool::ResolveToolPrivate::ParseHeader(const BamTools::SamHeader&)’:
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:1049:93: error: no matching function for call to ‘make_pair(const string&, ReadGroupResolver)’
         m_readGroups.insert( make_pair<string, ReadGroupResolver>(rg.ID, ReadGroupResolver()) );
                                                                                             ^
In file included from /usr/include/c++/6/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6/bits/char_traits.h:39,
                 from /usr/include/c++/6/string:40,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_tool.h:14,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.h:13,
                 from /home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:10:
/usr/include/c++/6/bits/stl_pair.h:493:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6/bits/stl_pair.h:493:5: note:   template argument deduction/substitution failed:
/home/garvan/Sources/ReadServer/submodules/bamtools/src/toolkit/bamtools_resolve.cpp:1049:70: note:   cannot convert ‘rg.BamTools::SamReadGroup::ID’ (type ‘const string {aka const std::__cxx11::basic_string<char>}’) to type ‘std::__cxx11::basic_string<char>&&’
         m_readGroups.insert( make_pair<string, ReadGroupResolver>(rg.ID, ReadGroupResolver()) );
                                                                   ~~~^~
src/toolkit/CMakeFiles/bamtools_cmd.dir/build.make:254: recipe for target 'src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o' failed
make[2]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o] Error 1
CMakeFiles/Makefile2:520: recipe for target 'src/toolkit/CMakeFiles/bamtools_cmd.dir/all' failed
make[1]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Zhicheng-Liu** [comment]
Can we close this one now? It looks like a compiler version issue for me. If you have resolved this issue, I would appreciate if you could let us know what the problem was and what was your solution.
Thank you very much!

**Comment by student-t** [comment]
That was my problem on my machine. Sorry.
